// @swarm-press/toolgraph runtime: generated by scripts/build-runtime.ts. Do not edit.
(() => {
  // ../sdk/src/runtime.ts
  var CREDENTIAL_HEADER = "X-SwarmPress-Credential";

  class CapabilityMissing extends Error {
    constructor(what) {
      super(`capability not granted: ${what}`);
      this.name = "CapabilityError";
    }
  }
  var g = globalThis;
  function storeFacade() {
    return {
      table(name) {
        const path = (key) => `store/${name}/${key}.json`;
        return {
          async get(key) {
            const f = Bun.file(path(key));
            return await f.exists() ? await f.json() : null;
          },
          async put(key, value) {
            await Bun.write(path(key), JSON.stringify(value));
          }
        };
      }
    };
  }
  function webFacade(credentialRef) {
    return {
      async fetch(url, init) {
        if (typeof g.fetch !== "function")
          throw new CapabilityMissing("web");
        const headers = { ...init?.headers ?? {} };
        if (credentialRef)
          headers[CREDENTIAL_HEADER] = credentialRef;
        return g.fetch(url, { ...init, headers });
      }
    };
  }
  function llmFacade() {
    return {
      async complete(req) {
        if (typeof swarmpress === "undefined" || !swarmpress?.llm)
          throw new CapabilityMissing(`llm:${req.tier}`);
        return swarmpress.llm.complete(req);
      }
    };
  }
  var log = {
    info: (...a) => console.log(...a),
    warn: (...a) => console.warn(...a),
    error: (...a) => console.error(...a)
  };
  function hostContext() {
    return { store: storeFacade(), llm: llmFacade(), web: webFacade(), log };
  }
  function defineSkill(def) {
    const tools = def.tools ?? {};
    const jobs = def.jobs ?? {};
    return {
      kind: "skill",
      tools,
      jobs,
      describe() {
        const t = {};
        for (const k of Object.keys(tools).sort())
          t[k] = { description: tools[k].description, input: tools[k].input };
        const j = {};
        for (const k of Object.keys(jobs).sort())
          j[k] = { description: jobs[k].description, example: jobs[k].example };
        return { tools: t, jobs: j };
      },
      async runJob({ job }) {
        const def2 = jobs[job.kind];
        if (!def2)
          throw new Error(`no job handler for kind ${JSON.stringify(job.kind)}`);
        return await def2.handler({ ...hostContext(), job });
      },
      async runTool({ tool, input }) {
        const def2 = tools[tool];
        if (!def2)
          throw new Error(`no tool ${JSON.stringify(tool)}`);
        return await def2.run(input, hostContext());
      }
    };
  }
  function canonicalJson(value) {
    if (value === null || typeof value !== "object") {
      if (typeof value === "number" && !Number.isFinite(value))
        throw new Error("canonicalJson: non-finite number");
      return JSON.stringify(value === undefined ? null : value);
    }
    if (Array.isArray(value))
      return `[${value.map(canonicalJson).join(",")}]`;
    const o = value;
    const keys = Object.keys(o).filter((k) => o[k] !== undefined).sort();
    return `{${keys.map((k) => `${JSON.stringify(k)}:${canonicalJson(o[k])}`).join(",")}}`;
  }
  function utf8(s) {
    const out = [];
    for (let i = 0;i < s.length; i++) {
      let c = s.charCodeAt(i);
      if (c >= 55296 && c <= 56319 && i + 1 < s.length) {
        const d = s.charCodeAt(i + 1);
        if (d >= 56320 && d <= 57343) {
          c = 65536 + (c - 55296 << 10) + (d - 56320);
          i++;
        }
      }
      if (c < 128)
        out.push(c);
      else if (c < 2048)
        out.push(192 | c >> 6, 128 | c & 63);
      else if (c < 65536)
        out.push(224 | c >> 12, 128 | c >> 6 & 63, 128 | c & 63);
      else
        out.push(240 | c >> 18, 128 | c >> 12 & 63, 128 | c >> 6 & 63, 128 | c & 63);
    }
    return out;
  }
  var K = [
    1116352408,
    1899447441,
    3049323471,
    3921009573,
    961987163,
    1508970993,
    2453635748,
    2870763221,
    3624381080,
    310598401,
    607225278,
    1426881987,
    1925078388,
    2162078206,
    2614888103,
    3248222580,
    3835390401,
    4022224774,
    264347078,
    604807628,
    770255983,
    1249150122,
    1555081692,
    1996064986,
    2554220882,
    2821834349,
    2952996808,
    3210313671,
    3336571891,
    3584528711,
    113926993,
    338241895,
    666307205,
    773529912,
    1294757372,
    1396182291,
    1695183700,
    1986661051,
    2177026350,
    2456956037,
    2730485921,
    2820302411,
    3259730800,
    3345764771,
    3516065817,
    3600352804,
    4094571909,
    275423344,
    430227734,
    506948616,
    659060556,
    883997877,
    958139571,
    1322822218,
    1537002063,
    1747873779,
    1955562222,
    2024104815,
    2227730452,
    2361852424,
    2428436474,
    2756734187,
    3204031479,
    3329325298
  ];
  function sha256HexBytes(bytes) {
    const len = bytes.length;
    const total = len + 9 + 63 >> 6 << 6;
    const m = new Uint8Array(total);
    for (let i = 0;i < len; i++)
      m[i] = bytes[i];
    m[len] = 128;
    const bits = len * 8;
    const hi = Math.floor(bits / 4294967296);
    const lo = bits >>> 0;
    m[total - 8] = hi >>> 24;
    m[total - 7] = hi >>> 16 & 255;
    m[total - 6] = hi >>> 8 & 255;
    m[total - 5] = hi & 255;
    m[total - 4] = lo >>> 24;
    m[total - 3] = lo >>> 16 & 255;
    m[total - 2] = lo >>> 8 & 255;
    m[total - 1] = lo & 255;
    const h = [1779033703, 3144134277, 1013904242, 2773480762, 1359893119, 2600822924, 528734635, 1541459225];
    const w = new Array(64);
    for (let off = 0;off < total; off += 64) {
      for (let i = 0;i < 16; i++) {
        const j = off + i * 4;
        w[i] = m[j] << 24 | m[j + 1] << 16 | m[j + 2] << 8 | m[j + 3] | 0;
      }
      for (let i = 16;i < 64; i++) {
        const a2 = w[i - 15], b2 = w[i - 2];
        const s0 = (a2 >>> 7 | a2 << 25) ^ (a2 >>> 18 | a2 << 14) ^ a2 >>> 3;
        const s1 = (b2 >>> 17 | b2 << 15) ^ (b2 >>> 19 | b2 << 13) ^ b2 >>> 10;
        w[i] = w[i - 16] + s0 + w[i - 7] + s1 | 0;
      }
      let [a, b, c, d, e, f, g2, hh] = h;
      for (let i = 0;i < 64; i++) {
        const S1 = (e >>> 6 | e << 26) ^ (e >>> 11 | e << 21) ^ (e >>> 25 | e << 7);
        const ch = e & f ^ ~e & g2;
        const t1 = hh + S1 + ch + K[i] + w[i] | 0;
        const S0 = (a >>> 2 | a << 30) ^ (a >>> 13 | a << 19) ^ (a >>> 22 | a << 10);
        const maj = a & b ^ a & c ^ b & c;
        const t2 = S0 + maj | 0;
        hh = g2;
        g2 = f;
        f = e;
        e = d + t1 | 0;
        d = c;
        c = b;
        b = a;
        a = t1 + t2 | 0;
      }
      h[0] = h[0] + a | 0;
      h[1] = h[1] + b | 0;
      h[2] = h[2] + c | 0;
      h[3] = h[3] + d | 0;
      h[4] = h[4] + e | 0;
      h[5] = h[5] + f | 0;
      h[6] = h[6] + g2 | 0;
      h[7] = h[7] + hh | 0;
    }
    return h.map((x) => (x >>> 0).toString(16).padStart(8, "0")).join("");
  }
  function sha256Hex(text) {
    return sha256HexBytes(utf8(text));
  }

  // src/types.ts
  class TypeSchemaError extends Error {
    issues;
    constructor(issues) {
      super(issues.map((i) => `${i.path}: ${i.message}`).join("; "));
      this.name = "TypeSchemaError";
      this.issues = issues;
    }
  }
  var MAX_DEPTH = 16;
  function parseTypeExpr(s) {
    let rest = s;
    let optional = false;
    let list = false;
    if (rest.endsWith("?")) {
      optional = true;
      rest = rest.slice(0, -1);
    }
    if (rest.endsWith("[]")) {
      list = true;
      rest = rest.slice(0, -2);
    }
    if (!/^[A-Za-z][A-Za-z0-9]{0,63}$/.test(rest)) {
      throw new TypeSchemaError([{ path: "$", message: `${JSON.stringify(s)} is not a type expression (Name, Name[], Name? or Name[]?)` }]);
    }
    return { name: rest, list, optional };
  }
  var S = { t: "string" };
  var LOC = { t: "localized" };
  var obj = (fields) => ({
    t: "object",
    fields: Object.fromEntries(fields.map(([n, ty, required]) => [n, { ty, required }]))
  });
  function builtins() {
    const page = [
      ["id", S, true],
      ["path", S, true],
      ["page_type", S, true],
      ["route", S, true],
      ["title", LOC, true]
    ];
    const article = [...page, ["published_at", S, false], ["hero", { t: "ref", name: "Media" }, false]];
    const entity = [
      ["slug", S, true],
      ["name", S, true],
      ["canonical_url", S, false]
    ];
    const out = {
      string: { t: "string" },
      integer: { t: "integer" },
      number: { t: "number" },
      boolean: { t: "boolean" },
      LocalizedString: LOC,
      Media: obj([
        ["id", S, true],
        ["url", S, true],
        ["alt", LOC, false]
      ]),
      Page: obj(page),
      Article: obj(article),
      FeedItem: obj([
        ["title", S, true],
        ["link", S, true],
        ["published", S, false],
        ["summary", S, false]
      ]),
      SearchResult: obj([
        ["title", S, true],
        ["url", S, true],
        ["snippet", S, false]
      ])
    };
    for (const kind of ["Village", "Trail", "Transport", "Category"])
      out[kind] = obj(entity);
    return out;
  }
  var SCHEMA_KEYS = new Set(["type", "items", "properties", "required", "additionalProperties", "description", "title"]);
  function parseSchema(v, path) {
    const bad = (message) => new TypeSchemaError([{ path, message }]);
    if (v === null || typeof v !== "object" || Array.isArray(v))
      throw bad("a type is a JSON Schema object");
    const o = v;
    if ("$ref" in o) {
      const raw = typeof o.$ref === "string" ? o.$ref : "";
      const name = raw.startsWith("#/types/") ? raw.slice(8) : raw;
      parseTypeExpr(name);
      return { t: "ref", name };
    }
    if ("enum" in o) {
      const values = Array.isArray(o.enum) ? o.enum : [];
      const strs = values.filter((x) => typeof x === "string");
      const set = [...new Set(strs)].sort();
      if (set.length === 0 || set.length !== values.length)
        throw bad("an enum lists distinct strings");
      return { t: "enum", values: set };
    }
    const unknown = Object.keys(o).find((k) => !SCHEMA_KEYS.has(k));
    if (unknown !== undefined)
      throw bad(`\`${unknown}\` is outside the type subset`);
    switch (o.type) {
      case "string":
      case "integer":
      case "number":
      case "boolean":
        return { t: o.type };
      case "array":
        if (!("items" in o))
          throw bad("an array names its items");
        return { t: "array", items: parseSchema(o.items, `${path}/items`) };
      case "object": {
        if (o.additionalProperties !== false)
          throw bad('an object is closed: "additionalProperties": false');
        const required = new Set((Array.isArray(o.required) ? o.required : []).filter((x) => typeof x === "string"));
        const props = o.properties && typeof o.properties === "object" && !Array.isArray(o.properties) ? o.properties : {};
        const fields = {};
        const issues = [];
        for (const name of Object.keys(props).sort()) {
          try {
            fields[name] = { ty: parseSchema(props[name], `${path}/properties/${name}`), required: required.has(name) };
          } catch (e) {
            if (e instanceof TypeSchemaError)
              issues.push(...e.issues);
            else
              throw e;
          }
        }
        for (const r of [...required].sort())
          if (!(r in fields))
            issues.push({ path, message: `required field ${r} has no property` });
        if (issues.length)
          throw new TypeSchemaError(issues);
        return { t: "object", fields };
      }
      case undefined:
        throw bad("a type names its `type`, `enum` or `$ref`");
      default:
        throw bad(`type ${JSON.stringify(o.type)} is outside the subset`);
    }
  }
  function collectRefs(t, out) {
    if (t.t === "ref")
      out.add(t.name);
    else if (t.t === "array")
      collectRefs(t.items, out);
    else if (t.t === "object")
      for (const f of Object.values(t.fields))
        collectRefs(f.ty, out);
  }

  class TypeRegistry {
    types;
    builtin;
    constructor(types, builtin) {
      this.types = types;
      this.builtin = builtin;
    }
    static builtins() {
      const b = builtins();
      return new TypeRegistry(b, new Set(Object.keys(b)));
    }
    static withSite(site) {
      const reg = TypeRegistry.builtins();
      const issues = [];
      for (const name of Object.keys(site).sort()) {
        const path = `/types/${name}`;
        try {
          const e = parseTypeExpr(name);
          if (e.list || e.optional)
            throw new TypeSchemaError([{ path, message: `${JSON.stringify(name)} is a name, not an expression` }]);
        } catch (e) {
          if (!(e instanceof TypeSchemaError))
            throw e;
          issues.push({ path, message: e.issues[0].message });
          continue;
        }
        if (reg.builtin.has(name)) {
          issues.push({ path, message: `${name} is a built-in type` });
          continue;
        }
        try {
          reg.types[name] = parseSchema(site[name], path);
        } catch (e) {
          if (e instanceof TypeSchemaError)
            issues.push(...e.issues);
          else
            throw e;
        }
      }
      for (const name of Object.keys(reg.types).sort()) {
        const refs = new Set;
        collectRefs(reg.types[name], refs);
        for (const r of [...refs].sort())
          if (!(r in reg.types))
            issues.push({ path: `/types/${name}`, message: `${name} refers to ${r}, which is not a type` });
      }
      if (issues.length)
        throw new TypeSchemaError(issues);
      return reg;
    }
    get(name) {
      return Object.prototype.hasOwnProperty.call(this.types, name) ? this.types[name] : undefined;
    }
    names() {
      return Object.keys(this.types).sort();
    }
    knows(e) {
      const t = typeof e === "string" ? parseTypeExpr(e) : e;
      return this.get(t.name) !== undefined;
    }
    resolve(t) {
      let cur = t;
      for (let i = 0;i < MAX_DEPTH && cur; i++) {
        if (cur.t !== "ref")
          return cur;
        cur = this.get(cur.name);
      }
      return;
    }
    validate(value, typeExpr) {
      let e;
      try {
        e = typeof typeExpr === "string" ? parseTypeExpr(typeExpr) : typeExpr;
      } catch (err) {
        if (err instanceof TypeSchemaError)
          return err.issues;
        throw err;
      }
      const issues = [];
      if (this.get(e.name) === undefined)
        return [{ path: "$", message: `${e.name} is not a type` }];
      if (e.optional && (value === null || value === undefined))
        return issues;
      const base = { t: "ref", name: e.name };
      this.check(value, e.list ? { t: "array", items: base } : base, "$", 0, issues);
      return issues;
    }
    check(v, ty, at, depth, out) {
      if (depth > MAX_DEPTH) {
        out.push({ path: at, message: "the value nests too deeply" });
        return;
      }
      const t = this.resolve(ty);
      if (!t) {
        out.push({ path: at, message: "a reference does not resolve" });
        return;
      }
      const want = (what) => {
        out.push({ path: at, message: `expected ${what}, found ${describe(v)}` });
      };
      switch (t.t) {
        case "string":
          if (typeof v !== "string")
            want("a string");
          return;
        case "integer":
          if (typeof v !== "number" || !Number.isInteger(v))
            want("an integer");
          return;
        case "number":
          if (typeof v !== "number" || !Number.isFinite(v))
            want("a number");
          return;
        case "boolean":
          if (typeof v !== "boolean")
            want("a boolean");
          return;
        case "enum":
          if (typeof v !== "string" || !t.values.includes(v))
            want(`one of ${t.values.join(", ")}`);
          return;
        case "localized": {
          if (typeof v === "string")
            return;
          if (!isObject(v))
            return want("a LocalizedString");
          if (!("en" in v))
            out.push({ path: `${at}.en`, message: "missing (a LocalizedString needs en)" });
          for (const k of Object.keys(v).sort())
            if (typeof v[k] !== "string")
              out.push({ path: `${at}.${k}`, message: `expected a string, found ${describe(v[k])}` });
          return;
        }
        case "array":
          if (!Array.isArray(v))
            return want("an array");
          v.forEach((item, i) => this.check(item, t.items, `${at}[${i}]`, depth + 1, out));
          return;
        case "object": {
          if (!isObject(v))
            return want("an object");
          for (const name of Object.keys(t.fields).sort()) {
            const f = t.fields[name];
            const fv = v[name];
            if (fv === undefined) {
              if (f.required)
                out.push({ path: `${at}.${name}`, message: "missing" });
              continue;
            }
            this.check(fv, f.ty, `${at}.${name}`, depth + 1, out);
          }
          for (const k of Object.keys(v).sort())
            if (!(k in t.fields))
              out.push({ path: `${at}.${k}`, message: "not a field of this type" });
          return;
        }
        case "ref":
          return;
      }
    }
    jsonSchema(typeExpr) {
      const e = typeof typeExpr === "string" ? parseTypeExpr(typeExpr) : typeExpr;
      const base = this.schemaOf({ t: "ref", name: e.name }, 0);
      return e.list ? { type: "array", items: base } : base;
    }
    schemaOf(ty, depth) {
      if (depth > MAX_DEPTH)
        return {};
      const t = this.resolve(ty);
      if (!t)
        return {};
      switch (t.t) {
        case "string":
        case "integer":
        case "number":
        case "boolean":
          return { type: t.t };
        case "localized":
          return {
            type: "object",
            required: ["en"],
            properties: { en: { type: "string" } },
            additionalProperties: { type: "string" },
            description: "LocalizedString: language code → text, en required"
          };
        case "enum":
          return { enum: [...t.values] };
        case "array":
          return { type: "array", items: this.schemaOf(t.items, depth + 1) };
        case "object": {
          const names = Object.keys(t.fields).sort();
          const properties = {};
          for (const n of names)
            properties[n] = this.schemaOf(t.fields[n].ty, depth + 1);
          return { type: "object", additionalProperties: false, required: names.filter((n) => t.fields[n].required), properties };
        }
        case "ref":
          return {};
      }
    }
  }
  function isObject(v) {
    return v !== null && typeof v === "object" && !Array.isArray(v);
  }
  function describe(v) {
    if (v === null)
      return "null";
    if (v === undefined)
      return "nothing";
    if (Array.isArray(v))
      return "an array";
    if (typeof v === "number")
      return Number.isInteger(v) ? "an integer" : "a number";
    return typeof v === "object" ? "an object" : `a ${typeof v}`;
  }

  class PathError extends Error {
    constructor(path, why) {
      super(`${JSON.stringify(path)} is not a path: ${why}`);
      this.name = "PathError";
    }
  }
  function parsePath(path) {
    if (!path.startsWith("$"))
      throw new PathError(path, "a path starts with $");
    const steps = [];
    let rest = path.slice(1);
    while (rest.length) {
      if (rest.startsWith(".")) {
        const r = rest.slice(1);
        const m = /[.[]/.exec(r);
        const end = m ? m.index : r.length;
        const name = r.slice(0, end);
        if (!name)
          throw new PathError(path, "an empty field name");
        steps.push({ k: "field", name });
        rest = r.slice(end);
      } else if (rest.startsWith("[")) {
        const end = rest.indexOf("]");
        if (end < 0)
          throw new PathError(path, "an unclosed [");
        const idx = rest.slice(1, end);
        if (idx === "")
          steps.push({ k: "each" });
        else if (/^[0-9]+$/.test(idx))
          steps.push({ k: "index", i: Number(idx) });
        else
          throw new PathError(path, `[${idx}] is not an index`);
        rest = rest.slice(end + 1);
      } else {
        throw new PathError(path, `unexpected ${JSON.stringify(rest[0])}`);
      }
    }
    return steps;
  }
  function walk(v, steps, i) {
    if (i === steps.length)
      return v;
    const s = steps[i];
    if (v === null || v === undefined)
      return;
    if (s.k === "field") {
      if (!isObject(v) || !Object.prototype.hasOwnProperty.call(v, s.name))
        return;
      return walk(v[s.name], steps, i + 1);
    }
    if (!Array.isArray(v))
      return;
    if (s.k === "index")
      return s.i < v.length ? walk(v[s.i], steps, i + 1) : undefined;
    const out = [];
    for (const item of v) {
      const r = walk(item, steps, i + 1);
      if (r !== undefined)
        out.push(r);
    }
    return out;
  }
  function readPath(value, path) {
    return walk(value, parsePath(path), 0);
  }

  // src/interpret.ts
  class NodeError extends Error {
    issues;
    fatal;
    constructor(message, opts = {}) {
      super(message);
      this.name = "NodeError";
      this.issues = opts.issues;
      this.fatal = opts.fatal ?? false;
    }
  }
  function isCapabilityError(e) {
    return !!e && typeof e === "object" && e.name === "CapabilityError";
  }
  var sha = (v) => sha256Hex(canonicalJson(v));
  var errMsg = (e) => e instanceof Error ? e.message : String(e);
  function typeError(what, issues) {
    const head = issues.slice(0, 5).map((i) => `${i.path}: ${i.message}`).join("; ");
    return new NodeError(`${what}: ${head}${issues.length > 5 ? ` (+${issues.length - 5} more)` : ""}`, { issues });
  }
  function inPorts(n) {
    switch (n.kind) {
      case "input":
        return [];
      case "connector":
        return [["params", false]];
      case "op":
        if (n.op === "filter")
          return [
            ["in", true],
            ["param", false]
          ];
        if (n.op === "merge")
          return [
            ["in", true],
            ["b", true]
          ];
        return [["in", true]];
      default:
        return [["in", true]];
    }
  }
  function outPorts(n) {
    if (n.kind === "output")
      return [];
    if (n.kind === "condition")
      return n.test === "switch" ? [...n.cases, "else"] : ["yes", "no"];
    return ["out"];
  }
  function parseEdges(g2) {
    const ids = new Map(g2.nodes.map((n) => [n.id, n]));
    if (ids.size !== g2.nodes.length)
      throw new NodeError("bad-graph: a node id is used twice");
    const edges = [];
    const fed = new Set;
    g2.edges.forEach(([a, b], i) => {
      const da = a.indexOf(".");
      const db = b.indexOf(".");
      if (da < 0 || db < 0)
        throw new NodeError(`bad-graph: edge ${i} joins node.port to node.port`);
      const e = { from: a.slice(0, da), fromPort: a.slice(da + 1), to: b.slice(0, db), toPort: b.slice(db + 1) };
      const f = ids.get(e.from);
      const t = ids.get(e.to);
      if (!f || !outPorts(f).includes(e.fromPort))
        throw new NodeError(`bad-graph: edge ${i}: ${a} is not an outlet`);
      if (!t || !inPorts(t).some(([p]) => p === e.toPort))
        throw new NodeError(`bad-graph: edge ${i}: ${b} is not an inlet`);
      const key = `${e.to}.${e.toPort}`;
      if (fed.has(key))
        throw new NodeError(`bad-graph: ${key} is fed twice`);
      fed.add(key);
      edges.push(e);
    });
    for (const n of g2.nodes) {
      if (n.kind === "input" && !Object.prototype.hasOwnProperty.call(g2.inputs, n.port))
        throw new NodeError(`bad-graph: ${n.id} reads ${n.port}, which is not an input of the tool`);
      if (n.kind === "output" && !Object.prototype.hasOwnProperty.call(g2.outputs, n.port))
        throw new NodeError(`bad-graph: ${n.id} writes ${n.port}, which is not an output of the tool`);
    }
    for (const n of g2.nodes)
      for (const [p, required] of inPorts(n))
        if (required && !fed.has(`${n.id}.${p}`))
          throw new NodeError(`bad-graph: ${n.id}.${p} is not connected`);
    for (const n of g2.nodes)
      if (n.kind === "connector" && placeholders(n.url ?? n.query ?? "").length && !fed.has(`${n.id}.params`))
        throw new NodeError(`bad-graph: ${n.id} fills {${placeholders(n.url ?? n.query ?? "").join("}, {")}} from params, which is not connected`);
    return edges;
  }
  function topoOrder(g2, edges = parseEdges(g2)) {
    const indeg = new Map(g2.nodes.map((n) => [n.id, 0]));
    for (const e of edges)
      if (indeg.has(e.from) && indeg.has(e.to))
        indeg.set(e.to, indeg.get(e.to) + 1);
    const ready = g2.nodes.map((n) => n.id).filter((id) => indeg.get(id) === 0);
    const out = [];
    while (ready.length) {
      const id = ready.shift();
      out.push(id);
      for (const e of edges) {
        if (e.from !== id || !indeg.has(e.to))
          continue;
        const d = indeg.get(e.to) - 1;
        indeg.set(e.to, d);
        if (d === 0)
          ready.push(e.to);
      }
    }
    if (out.length !== indeg.size)
      throw new NodeError("bad-graph: the graph has a cycle");
    return out;
  }
  var isObj = (v) => v !== null && typeof v === "object" && !Array.isArray(v);
  var clone = (v) => v === undefined ? v : JSON.parse(JSON.stringify(v));
  function compare(a, cmp, b) {
    const eq = (x, y) => x !== undefined && canonicalJson(x) === canonicalJson(y);
    switch (cmp) {
      case "eq":
        return eq(a, b);
      case "ne":
        return !eq(a, b);
      case "gt":
      case "lt": {
        const same = typeof a === "number" && typeof b === "number" || typeof a === "string" && typeof b === "string";
        if (!same)
          return false;
        return cmp === "gt" ? a > b : a < b;
      }
      case "contains":
        if (typeof a === "string" && typeof b === "string")
          return a.includes(b);
        if (Array.isArray(a))
          return a.some((x) => eq(x, b));
        return false;
    }
  }
  function sortRank(v) {
    if (typeof v === "number")
      return 0;
    if (typeof v === "string")
      return 1;
    return v === undefined || v === null ? 3 : 2;
  }
  function sortCompare(a, b) {
    const ra = sortRank(a);
    const rb = sortRank(b);
    if (ra !== rb)
      return ra - rb;
    if (ra === 0)
      return a - b;
    if (ra === 1)
      return a < b ? -1 : a > b ? 1 : 0;
    if (ra === 2) {
      const ca = canonicalJson(a);
      const cb = canonicalJson(b);
      return ca < cb ? -1 : ca > cb ? 1 : 0;
    }
    return 0;
  }
  function placeholders(t) {
    return t.split("{").slice(1).flatMap((p) => {
      const end = p.indexOf("}");
      return end < 0 ? [] : [p.slice(0, end)];
    });
  }
  function originOf(url) {
    if (!url.startsWith("https://"))
      return null;
    const rest = url.slice(8);
    const m = /[/?#]/.exec(rest);
    const host = rest.slice(0, m ? m.index : rest.length);
    return host && /^[A-Za-z0-9.:-]+$/.test(host) && host.includes(".") ? `https://${host}` : null;
  }
  function scalarText(v, what) {
    if (typeof v === "string")
      return v;
    if (typeof v === "number" || typeof v === "boolean")
      return String(v);
    throw new NodeError(`${what} is ${v === undefined ? "missing" : "not a string, number or boolean"}`);
  }
  function fillTemplate(template, params, encode) {
    const names = [...new Set(placeholders(template))];
    if (!names.length)
      return template;
    const scalar = !isObj(params) && names.length === 1;
    return template.replace(/\{([^{}]*)\}/g, (_, name) => {
      const v = scalar ? params : isObj(params) ? readPath(params, `$.${name}`) : undefined;
      const s = scalarText(v, `placeholder {${name}}`);
      return encode ? encodeURIComponent(s) : s;
    });
  }
  function formatTemplate(template, value) {
    return template.replace(/\{([^{}]*)\}/g, (_, raw) => {
      const p = raw.trim();
      const path = p === "" || p === "$" ? "$" : p.startsWith("$") ? p : `$.${p}`;
      const v = readPath(value, path);
      if (v === undefined)
        throw new NodeError(`format: {${raw}} is not in the value`);
      return typeof v === "string" ? v : canonicalJson(v);
    });
  }
  var ENTITIES = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: " " };
  function decodeXmlText(raw) {
    let out = "";
    const re = /<!\[CDATA\[([\s\S]*?)\]\]>/g;
    let last = 0;
    let m;
    const decode = (s) => s.replace(/&(#x[0-9a-fA-F]+|#[0-9]+|[a-zA-Z]+);/g, (whole, e) => {
      if (e[0] === "#") {
        const code = e[1] === "x" || e[1] === "X" ? parseInt(e.slice(2), 16) : parseInt(e.slice(1), 10);
        return Number.isFinite(code) && code > 0 && code <= 1114111 ? String.fromCodePoint(code) : whole;
      }
      return ENTITIES[e] ?? whole;
    });
    while (m = re.exec(raw)) {
      out += decode(raw.slice(last, m.index)) + m[1];
      last = m.index + m[0].length;
    }
    out += decode(raw.slice(last));
    return out.trim();
  }
  function tagText(xml, names) {
    for (const name of names) {
      const esc = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const m = new RegExp(`<${esc}(?:\\s[^>]*)?>([\\s\\S]*?)</${esc}\\s*>`).exec(xml);
      if (m) {
        const t = decodeXmlText(m[1]);
        if (t)
          return t;
      }
    }
    return;
  }
  function parseFeed(xml) {
    const items = [];
    const re = /<(item|entry)(?:\s[^>]*)?>([\s\S]*?)<\/\1\s*>/g;
    let m;
    while (m = re.exec(xml)) {
      const body = m[2];
      const item = {};
      const title = tagText(body, ["title"]);
      let link = tagText(body, ["link"]);
      if (!link) {
        const links = [...body.matchAll(/<link\b([^>]*?)\/?>/g)].map((l) => l[1]);
        const pick = links.find((a) => !/\brel\s*=/.test(a) || /\brel\s*=\s*["']alternate["']/.test(a)) ?? links[0];
        const href = pick && /\bhref\s*=\s*["']([^"']*)["']/.exec(pick);
        if (href)
          link = decodeXmlText(href[1]);
      }
      const published = tagText(body, ["pubDate", "published", "updated", "dc:date"]);
      const summary = tagText(body, ["description", "summary"]);
      if (title !== undefined)
        item.title = title;
      if (link !== undefined)
        item.link = link;
      if (published !== undefined)
        item.published = published;
      if (summary !== undefined)
        item.summary = summary;
      items.push(item);
    }
    return items;
  }
  function parseJsonReply(text) {
    let t = text.trim();
    const fence = /^```[a-zA-Z]*\s*\n?([\s\S]*?)\n?```$/.exec(t);
    if (fence)
      t = fence[1].trim();
    return JSON.parse(t);
  }
  async function runGraph(graph, types, input, host, opts = {}) {
    const clock = opts.clock ?? (() => 0);
    const trace = [];
    const recorded = {};
    const keepLast = graph.failure.on_error === "keep-last";
    const fail = (error, issues) => ({
      ok: false,
      outputs: {},
      trace,
      recorded,
      error,
      ...issues ? { issues } : {},
      ...keepLast ? { keepLast: true } : {}
    });
    let reg;
    let edges;
    let order;
    try {
      reg = types instanceof TypeRegistry ? types : TypeRegistry.withSite(types);
      edges = parseEdges(graph);
      order = topoOrder(graph, edges);
    } catch (e) {
      if (e instanceof TypeSchemaError)
        return fail(`bad-types: ${e.message}`, e.issues);
      return fail(errMsg(e));
    }
    if (!isObj(input))
      return fail("bad-input: the input is an object of the tool's inputs");
    for (const k of Object.keys(input).sort())
      if (!(k in graph.inputs))
        return fail(`bad-input:${k}: not an input of ${graph.id}`);
    for (const port of Object.keys(graph.inputs).sort()) {
      const issues = reg.validate(input[port], graph.inputs[port]).map((i) => ({ path: `${port}${i.path.slice(1)}`, message: i.message }));
      if (issues.length)
        return fail(`bad-input:${port}: ${issues.map((i) => `${i.path}: ${i.message}`).join("; ")}`, issues);
    }
    const retries = graph.failure.retries;
    const count = (k) => graph.nodes.filter((n) => n.kind === k).length;
    const fetchLimit = graph.limits.fetches_per_run || count("connector") * (1 + retries);
    const llmLimit = graph.limits.llm_calls_per_run || count("agent") * (1 + retries) * 2;
    let fetches = 0;
    let llmCalls = 0;
    const spendFetch = () => {
      if (fetches >= fetchLimit)
        throw new NodeError(`limit:fetches_per_run: more than ${fetchLimit} calls`, { fatal: true });
      fetches++;
    };
    const spendLlm = () => {
      if (llmCalls >= llmLimit)
        throw new NodeError(`limit:llm_calls_per_run: more than ${llmLimit} calls`, { fatal: true });
      llmCalls++;
    };
    const need = (k) => {
      const f = host[k];
      if (typeof f !== "function")
        throw new NodeError(`no-host:${k}: this host does not provide ${k}`, { fatal: true });
      return f.bind(host);
    };
    const checked = (value, typeExpr, what) => {
      const issues = reg.validate(value, typeExpr);
      if (issues.length)
        throw typeError(`${what} does not fit ${typeExpr}`, issues);
      return value;
    };
    const withRetries = async (fn) => {
      let last;
      for (let attempt = 0;attempt <= retries; attempt++) {
        try {
          return await fn();
        } catch (e) {
          if (isCapabilityError(e) || e instanceof NodeError && e.fatal)
            throw e;
          last = e;
        }
      }
      throw last;
    };
    const replayed = (id) => opts.replay !== undefined && Object.prototype.hasOwnProperty.call(opts.replay, id);
    const nodes = new Map(graph.nodes.map((n) => [n.id, n]));
    const values = new Map;
    const outputs = {};
    for (const id of order) {
      const n = nodes.get(id);
      const inlets = {};
      let taken = true;
      for (const [port] of inPorts(n)) {
        const e = edges.find((x) => x.to === id && x.toPort === port);
        if (!e)
          continue;
        const key = `${e.from}.${e.fromPort}`;
        if (!values.has(key))
          taken = false;
        else
          inlets[port] = values.get(key);
      }
      if (!taken) {
        trace.push({ node: id, state: "not-taken", in_sha: null, out_sha: null, ms: 0 });
        continue;
      }
      if (n.kind === "input")
        inlets[n.port] = input[n.port];
      const inSha = sha(inlets);
      const t0 = clock();
      try {
        const { value, outlet } = await step(n, inlets);
        const entry = { node: id, state: "ok", in_sha: inSha, out_sha: sha(value), ms: clock() - t0 };
        if (n.kind === "condition")
          entry.outlet = outlet;
        trace.push(entry);
        if (n.kind === "output")
          outputs[n.port] = value;
        else
          values.set(`${id}.${outlet}`, value);
      } catch (e) {
        if (isCapabilityError(e))
          throw e;
        const issues = e instanceof NodeError ? e.issues : undefined;
        trace.push({ node: id, state: "failed", in_sha: inSha, out_sha: null, ms: clock() - t0, error: errMsg(e), ...issues ? { issues } : {} });
        return fail(`${id}: ${errMsg(e)}`, issues);
      }
    }
    for (const port of Object.keys(graph.outputs).sort())
      if (!(port in outputs))
        return fail(`no-output:${port}`);
    return { ok: true, outputs, trace, recorded };
    async function step(n, inlets) {
      const out = (value) => ({ value, outlet: "out" });
      switch (n.kind) {
        case "input":
          return out(clone(inlets[n.port]));
        case "output":
          return { value: checked(clone(inlets.in), graph.outputs[n.port], `output ${n.port}`), outlet: "" };
        case "condition": {
          const v = readPath(inlets.in, n.path);
          let outlet;
          if (n.test === "exists")
            outlet = v !== undefined && v !== null ? "yes" : "no";
          else if (n.test === "compare")
            outlet = compare(v, n.cmp, n.value) ? "yes" : "no";
          else
            outlet = typeof v === "string" && n.cases.includes(v) ? v : "else";
          return { value: clone(inlets.in), outlet };
        }
        case "op":
          return out(op(n, inlets));
        case "connector":
          return out(await recordedCall(n.id, n.returns, () => connector(n, inlets.params)));
        case "skill":
          return out(await recordedCall(n.id, n.returns, async () => checked(await need("skill")(n.extension, n.tool, clone(inlets.in)), n.returns, `skill ${n.extension}/${n.tool}`)));
        case "agent":
          return out(await recordedCall(n.id, n.output, () => agent(n, inlets.in)));
      }
    }
    async function recordedCall(id, returns, call) {
      if (replayed(id)) {
        const v2 = checked(clone(opts.replay[id]), returns, "the recorded output");
        recorded[id] = v2;
        return clone(v2);
      }
      const v = await call();
      recorded[id] = clone(v);
      return v;
    }
    async function connector(n, params) {
      const what = `${n.connector} ${n.id}`;
      switch (n.connector) {
        case "http-get":
        case "rss": {
          const fetch = need("fetch");
          const template = n.url ?? "";
          const origin = originOf(template);
          if (!origin)
            throw new NodeError(`${what}: ${JSON.stringify(template)} is not an https URL with a literal host`, { fatal: true });
          const url = fillTemplate(template, params, true);
          const rest = url.slice(origin.length);
          if (!url.startsWith(origin) || !(rest === "" || "/?#".includes(rest[0])))
            throw new NodeError(`${what}: the filled URL left ${origin}`, { fatal: true });
          return withRetries(async () => {
            spendFetch();
            const body = await fetch(url, n.credential ? { credential: n.credential } : {});
            if (typeof body !== "string")
              throw new NodeError(`${what}: the host returned no text`);
            let v;
            if (n.connector === "rss")
              v = parseFeed(body);
            else {
              try {
                v = JSON.parse(body);
              } catch (e) {
                throw new NodeError(`${what}: the response is not JSON (${errMsg(e)})`);
              }
            }
            return checked(v, n.returns, what);
          });
        }
        case "web-search": {
          const search = need("search");
          const query = fillTemplate(n.query ?? "", params, false);
          return withRetries(async () => {
            spendFetch();
            return checked(await search(query), n.returns, what);
          });
        }
        case "knowledge": {
          const knowledge = need("knowledge");
          return withRetries(async () => {
            spendFetch();
            return checked(await knowledge(n.query ?? ""), n.returns, what);
          });
        }
        case "store-read": {
          const store = need("store");
          return withRetries(async () => {
            spendFetch();
            return checked(await store(n.table ?? "", typeof params === "string" ? params : undefined), n.returns, what);
          });
        }
        case "tool": {
          const tool = need("tool");
          return withRetries(async () => {
            spendFetch();
            return checked(await tool(n.tool ?? "", clone(params ?? {})), n.returns, what);
          });
        }
      }
    }
    async function agent(n, value) {
      const llm = need("llm");
      const prompt = agentPrompt(n.instruction, value, n.output, reg);
      return withRetries(async () => {
        spendLlm();
        const first = await llm(n.tier, prompt, { role: n.role, node: n.id });
        const a = judge(first, n.output);
        if (a.ok)
          return a.value;
        spendLlm();
        const second = await llm(n.tier, repairPrompt(prompt, first, a.problems), { role: n.role, node: n.id });
        const b = judge(second, n.output);
        if (b.ok)
          return b.value;
        throw new NodeError(`agent ${n.id}: the reply does not fit ${n.output} after a repair turn: ${b.problems.join("; ")}`, {
          issues: b.issues
        });
      });
    }
    function judge(text, output) {
      let v;
      try {
        if (typeof text !== "string")
          throw new Error("the reply is not text");
        v = parseJsonReply(text);
      } catch (e) {
        return { ok: false, problems: [`not JSON: ${errMsg(e)}`] };
      }
      const issues = reg.validate(v, output);
      return issues.length ? { ok: false, problems: issues.map((i) => `${i.path}: ${i.message}`), issues } : { ok: true, value: v };
    }
    function op(n, inlets) {
      const v = clone(inlets.in);
      const list = (what) => {
        if (!Array.isArray(v))
          throw new NodeError(`${n.op} ${n.id}: ${what} reads a list`);
        return v;
      };
      switch (n.op) {
        case "pick": {
          const got = readPath(v, n.path ?? "$");
          if (got === undefined)
            throw new NodeError(`pick ${n.id}: ${n.path} is not in the value`);
          return n.returns ? checked(got, n.returns, `pick ${n.id}`) : got;
        }
        case "map": {
          const items = list("map").map((item) => {
            const o = {};
            for (const field of Object.keys(n.fields).sort()) {
              const fv = readPath(item, n.fields[field]);
              if (fv !== undefined)
                o[field] = fv;
            }
            return o;
          });
          return n.returns ? checked(items, n.returns, `map ${n.id}`) : items;
        }
        case "filter": {
          const w = n.where;
          let rhs = w.value;
          if (typeof rhs === "string" && (rhs === "$param" || rhs.startsWith("$param."))) {
            if (!("param" in inlets))
              throw new NodeError(`filter ${n.id}: ${rhs} reads the param port, which is not connected`);
            rhs = readPath(inlets.param, `$${rhs.slice(6)}`);
            if (rhs === undefined)
              throw new NodeError(`filter ${n.id}: ${w.value} is not in the param value`);
          }
          return list("filter").filter((item) => compare(readPath(item, w.path), w.cmp, rhs));
        }
        case "sort": {
          const path = n.path ?? "$";
          const keyed = list("sort").map((item, i) => ({ item, key: readPath(item, path), i }));
          keyed.sort((a, b) => {
            const c = sortCompare(a.key, b.key);
            return (n.desc ? -c : c) || a.i - b.i;
          });
          return keyed.map((k) => k.item);
        }
        case "limit":
          return list("limit").slice(0, n.count ?? 0);
        case "merge": {
          const b = clone(inlets.b);
          if (!Array.isArray(b))
            throw new NodeError(`merge ${n.id}: b reads a list`);
          return [...list("merge"), ...b];
        }
        case "split": {
          const s = n.path ? readPath(v, n.path) : v;
          if (typeof s !== "string")
            throw new NodeError(`split ${n.id}: splits a string`);
          return s.split(n.separator ?? "");
        }
        case "format":
          return formatTemplate(n.template ?? "", v);
        case "validate":
          return checked(v, n.returns ?? "", `validate ${n.id}`);
      }
    }
  }
  function agentPrompt(instruction, input, output, reg) {
    return [
      instruction.trim(),
      "",
      "Input (JSON):",
      canonicalJson(input),
      "",
      `Reply with exactly one JSON value of type ${output} and nothing else. Its JSON Schema:`,
      canonicalJson(reg.jsonSchema(output))
    ].join(`
`);
  }
  function repairPrompt(prompt, reply, problems) {
    return [
      prompt,
      "",
      "Your previous reply was:",
      reply,
      "",
      "It does not fit the type:",
      ...problems.map((p) => `- ${p}`),
      "",
      "Reply again with only the corrected JSON value."
    ].join(`
`);
  }

  // src/skill.ts
  function contextHost(ctx, extra = {}) {
    return {
      async fetch(url, init) {
        const headers = {};
        if (init.credential)
          headers[CREDENTIAL_HEADER] = init.credential;
        const res = await ctx.web.fetch(url, { method: "GET", headers });
        if (!res.ok)
          throw new Error(`GET ${url}: HTTP ${res.status}`);
        return await res.text();
      },
      async llm(tier, prompt) {
        return (await ctx.llm.complete({ tier, prompt })).text;
      },
      async store(table, key) {
        return await ctx.store.table(table).get(key ?? "latest");
      },
      ...extra
    };
  }

  // src/runtime-entry.ts
  var runtime_entry_default = defineSkill({
    tools: {
      run: {
        description: "Runs a swarmpress.tool.v1 graph; the graph and its types are the call's data.",
        input: { type: "object" },
        async run(arg, ctx) {
          return await runGraph(arg.graph, TypeRegistry.withSite(arg.types), arg.input, contextHost(ctx), {
            clock: () => Date.now(),
            ...arg.replay ? { replay: arg.replay } : {}
          });
        }
      }
    }
  });

  // runtime/.entry.js
  globalThis.ext = runtime_entry_default;
})();
