//! The blueprint as a brick town (design §4): a `swarmpress.design.v1`
//! design generated by a pure function, the way room shells are generated
//! from the sim's rooms. The bricks are a view of the blueprint, never its
//! source: the design carries `provenance: view` with the blueprint's hash.
//!
//! Coordinates are the kit's `[x, z, y]`: studs east, studs south, plates up.
//! The town stands on a baseplate. Its page types are modular buildings in a
//! row along the main street (navigation order first, then declaration
//! order), fronts facing south:
//!
//! * a building is [`BUILDING`]×[`BUILDING`] studs;
//! * its foundation is the globals whose id names a footer, its roof the
//!   other globals it uses (2 plates each, coloured by the block's intent);
//! * between them, one storey per slot, bottom-up in page order: one brick
//!   high, two for a slot that repeats, coloured by the intent of the slot's
//!   first block; an optional slot is glass;
//! * a slot fed by a tool has a pipe stub on the back wall;
//! * a slot with a problem has a red corner column;
//! * a type that does not constrain its body is one grey storey.
//!
//! Relationships are walkways in front of the buildings, one lane each, from
//! door to door. Collections are warehouses behind the row: a stack of tiles
//! whose height grows with the item count (log scale). Tools, when given,
//! are machines in a factory district east of the town ([`crate::machines`]).

use std::collections::{BTreeMap, BTreeSet};

use content_model::{block_meta, Intent};
use kit::design::{Op, Provenance, Region};
use kit::expr::Num;
use kit::{Design, DESIGN_FORMAT};

use crate::format::{Blueprint, BlueprintPageType, Slot};
use crate::hash::hash;

pub const BUILDING: i64 = 8;
pub const GAP: i64 = 4;
pub const MARGIN: i64 = 4;
/// One storey: a brick (three plates).
pub const STOREY: i64 = 3;
pub const BAND: i64 = 2;
pub const WAREHOUSE: i64 = 6;
/// Most plates a warehouse's tile stack reaches.
pub const MAX_STACK: i64 = 10;

/// What else the town shows: problems per `type/slot`.
#[derive(Clone, Debug, Default)]
pub struct TownInput {
    /// `page-type/slot` ids with an issue (validation or the site audit).
    pub issues: BTreeSet<String>,
    /// The site's tools: machines in the factory district east of the town.
    pub tools: Vec<crate::machines::MachineInput>,
}

/// The brick colour of a block intent (fixed: players learn it).
pub fn intent_colour(intent: Intent) -> &'static str {
    match intent {
        Intent::Showcase => "orange",
        Intent::Inform => "blue",
        Intent::Navigate => "green",
        Intent::Convert => "red",
        Intent::Compare => "yellow",
        Intent::Orient => "sand",
        Intent::Engage => "plum",
    }
}

fn block_colour(block: &str) -> &'static str {
    block_meta(block).map_or("grey-light", |m| intent_colour(m.intent))
}

fn region(at: [i64; 3], size: [i64; 3], part: &str, colour: &str) -> Op {
    Op::Box(Region {
        at: at.map(Num::Int),
        size: size.map(Num::Int),
        part: part.into(),
        colour: Some(colour.into()),
        shape: Default::default(),
    })
}

fn slot_height(slot: &Slot) -> i64 {
    if slot.max.is_none_or(|m| m > 1) {
        STOREY * 2
    } else {
        STOREY
    }
}

/// The order buildings stand in: navigation first, then declaration.
fn street(bp: &Blueprint) -> Vec<&BlueprintPageType> {
    let mut seen = BTreeSet::new();
    let mut out = Vec::new();
    for n in &bp.navigation {
        if let Some(t) = n.page_type.as_deref().and_then(|id| bp.page_type(id)) {
            if seen.insert(t.id.as_str()) {
                out.push(t);
            }
        }
    }
    for t in &bp.page_types {
        if seen.insert(t.id.as_str()) {
            out.push(t);
        }
    }
    out
}

fn is_footer(global: &str) -> bool {
    global.contains("footer")
}

/// The ops of one building with its min corner at `(x, z)` on the baseplate
/// (`y = 1`); returns its height in plates.
fn building(
    bp: &Blueprint,
    t: &BlueprintPageType,
    x: i64,
    z: i64,
    input: &TownInput,
    ops: &mut Vec<Op>,
) -> i64 {
    let mut y = 1;
    let global_colour = |g: &str| {
        bp.globals
            .get(g)
            .map_or("grey-dark", |g| block_colour(&g.block))
    };
    let (footers, roofs): (Vec<&String>, Vec<&String>) = t.uses.iter().partition(|g| is_footer(g));
    for g in footers {
        ops.push(region(
            [x, z, y],
            [BUILDING, BUILDING, BAND],
            "plate",
            global_colour(g),
        ));
        y += BAND;
    }
    match &t.slots {
        None => {
            ops.push(region(
                [x, z, y],
                [BUILDING, BUILDING, STOREY],
                "brick",
                "grey-light",
            ));
            y += STOREY;
        }
        Some(slots) => {
            for slot in slots {
                let h = slot_height(slot);
                let first = slot.blocks.first().map_or("", String::as_str);
                let colour = if slot.min == 0 {
                    "glass"
                } else {
                    block_colour(first)
                };
                ops.push(region([x, z, y], [BUILDING, BUILDING, h], "brick", colour));
                if slot.source.is_some() {
                    // A pipe stub on the back wall (north, z - 1).
                    ops.push(region(
                        [x + BUILDING / 2 - 1, z - 1, y],
                        [2, 1, STOREY],
                        "brick",
                        "grey-dark",
                    ));
                }
                if input.issues.contains(&format!("{}/{}", t.id, slot.id)) {
                    ops.push(region([x, z + BUILDING - 1, y], [1, 1, h], "brick", "red"));
                }
                y += h;
            }
        }
    }
    for g in roofs {
        ops.push(region(
            [x, z, y],
            [BUILDING, BUILDING, BAND],
            "plate",
            global_colour(g),
        ));
        y += BAND;
    }
    // A door: an opening in the ground storey's front wall.
    if y > STOREY {
        ops.push(Op::Box(Region {
            at: [x + BUILDING / 2 - 1, z + BUILDING - 1, 1].map(Num::Int),
            size: [2, 1, STOREY.min(y - 1)].map(Num::Int),
            part: "empty".into(),
            colour: None,
            shape: Default::default(),
        }));
    }
    y
}

fn log2_ceil(n: u32) -> i64 {
    i64::from(32 - n.leading_zeros())
}

/// The blueprint's town.
pub fn town(bp: &Blueprint, input: &TownInput) -> Design {
    let buildings = street(bp);
    let n = buildings.len().max(1) as i64;
    let lanes = bp.relationships.len() as i64;
    let row_z = MARGIN + WAREHOUSE + GAP; // warehouses behind the row
    let street_z = row_z + BUILDING;
    let town_width = MARGIN * 2 + n * BUILDING + (n - 1) * GAP;
    // The factory district: one plot per tool, east of the town, in id order.
    let mut tools: Vec<&crate::machines::MachineInput> = input.tools.iter().collect();
    tools.sort_by(|a, b| a.graph.id.cmp(&b.graph.id));
    let plots: Vec<(i64, i64)> = tools
        .iter()
        .map(|m| crate::machines::plot_size(&m.graph))
        .collect();
    let factory_width: i64 = plots.iter().map(|(w, _)| w + GAP).sum();
    let width = town_width + factory_width;
    let depth = (street_z + 2 + lanes * 2 + MARGIN)
        .max(plots.iter().map(|(_, d)| d + 2 * MARGIN).max().unwrap_or(0));

    let mut ops = vec![region([0, 0, 0], [width, depth, 1], "plate", "green")];
    let mut door_x: BTreeMap<&str, i64> = BTreeMap::new();
    let mut height = 1;
    for (i, t) in buildings.iter().enumerate() {
        let x = MARGIN + i as i64 * (BUILDING + GAP);
        door_x.insert(t.id.as_str(), x + BUILDING / 2);
        height = height.max(building(bp, t, x, row_z, input, &mut ops));
    }
    // The street.
    ops.push(region(
        [0, street_z, 1],
        [town_width, 2, 1],
        "tile",
        "grey-dark",
    ));
    // The machines.
    let mut fx = town_width;
    for (m, (w, _)) in tools.iter().zip(&plots) {
        height = height.max(crate::machines::machine_ops(
            m, fx, MARGIN, region, &mut ops,
        ));
        fx += w + GAP;
    }
    // Walkways: one lane per relationship, door to door.
    for (k, r) in bp.relationships.iter().enumerate() {
        let (Some(&a), Some(&b)) = (door_x.get(r.from.as_str()), door_x.get(r.to.as_str())) else {
            continue;
        };
        let lane_z = street_z + 2 + k as i64 * 2;
        let (lo, hi) = (a.min(b), a.max(b));
        let colour = if r.from == r.to { "honey" } else { "sand" };
        ops.push(region([lo, lane_z, 1], [hi - lo + 1, 1, 1], "tile", colour));
        // Short legs from the lane up to the street at both doors.
        for x in [a, b] {
            ops.push(region(
                [x, street_z + 2, 1],
                [1, lane_z - street_z - 2 + 1, 1],
                "tile",
                colour,
            ));
        }
    }
    // Warehouses behind the buildings their collection draws from, the rest at the east end.
    let mut spare = 0;
    for c in &bp.collections {
        let behind = c
            .from
            .strip_prefix("page_type:")
            .and_then(|id| door_x.get(id))
            .copied();
        let x = match behind {
            Some(dx) => dx - WAREHOUSE / 2,
            None => {
                let x = town_width - MARGIN - WAREHOUSE - spare * (WAREHOUSE + 1);
                spare += 1;
                x.max(0)
            }
        };
        let stack = (1 + log2_ceil(c.items.unwrap_or(0))).min(MAX_STACK);
        ops.push(region(
            [x, MARGIN, 1],
            [WAREHOUSE, WAREHOUSE, 1],
            "plate",
            "grey-light",
        ));
        ops.push(region(
            [x + 1, MARGIN + 1, 2],
            [WAREHOUSE - 2, WAREHOUSE - 2, stack],
            "tile",
            "cork",
        ));
        height = height.max(2 + stack);
    }

    Design {
        schema: None,
        format: DESIGN_FORMAT.into(),
        id: "site-town".into(),
        name: "Site town".into(),
        mount: Default::default(),
        footprint: [Num::Int(width), Num::Int(depth)],
        height: Num::Int(height + 1),
        params: BTreeMap::new(),
        ops,
        ports: vec![],
        tags: vec![],
        budget: None,
        provenance: Provenance::View {
            source: "blueprint".into(),
            hash: hash(bp),
        },
    }
}
