/**
 * Builds `runtime/toolgraph-runtime.js`: the interpreter bundle the game loads
 * into a sandbox to run tools (an IIFE assigning `globalThis.ext`, built the
 * way `swarmpress build` builds extensions). Committed; `--check` fails when
 * the committed file is out of date (the test suite runs it).
 *
 *   bun scripts/build-runtime.ts [--check]
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const PKG = join(import.meta.dir, "..");
const ROOT = join(PKG, "..", "..");
const SDK_RUNTIME = join(ROOT, "packages", "sdk", "src", "runtime.ts");
export const RUNTIME = join(PKG, "runtime", "toolgraph-runtime.js");

const sdkPlugin = {
  name: "swarmpress-sdk",
  setup(b: { onResolve(o: { filter: RegExp }, cb: () => { path: string }): void }) {
    b.onResolve({ filter: /^@swarm-press\/sdk(\/runtime)?$/ }, () => ({ path: SDK_RUNTIME }));
  },
};

export async function buildRuntime(): Promise<string> {
  const entry = join(PKG, "runtime", ".entry.js");
  writeFileSync(entry, `import m from ${JSON.stringify(join(PKG, "src", "runtime-entry.ts"))};\nglobalThis.ext = m;\n`);
  try {
    const r = await Bun.build({ entrypoints: [entry], format: "iife", target: "browser", plugins: [sdkPlugin as never] });
    if (!r.success) throw new Error(r.logs.map(String).join("\n"));
    const text = await r.outputs[0].text();
    return `// @swarm-press/toolgraph runtime: generated by scripts/build-runtime.ts. Do not edit.\n${text.replaceAll(ROOT, "<root>")}`;
  } finally {
    (await import("node:fs")).rmSync(entry, { force: true });
  }
}

if (import.meta.main) {
  const text = await buildRuntime();
  if (process.argv.includes("--check")) {
    if (readFileSync(RUNTIME, "utf8") !== text) {
      console.error(`${RUNTIME} is out of date: run bun scripts/build-runtime.ts`);
      process.exit(1);
    }
    console.log("toolgraph-runtime.js is up to date");
  } else {
    writeFileSync(RUNTIME, text);
    console.log(`wrote ${RUNTIME} (${text.length} bytes)`);
  }
}
