/**
 * Blueprint Collection Types
 * Zod schemas and types for collection embedding in blueprints
 */

import { z } from 'zod'

// =============================================================================
// COLLECTION EMBED CONFIGURATION
// =============================================================================

/**
 * Display layout options for collection embeds
 */
export const CollectionDisplayLayoutSchema = z.enum([
  'grid',
  'list',
  'carousel',
  'table',
  'cards',
])
export type CollectionDisplayLayout = z.infer<typeof CollectionDisplayLayoutSchema>

/**
 * Display configuration for collection embeds
 */
export const CollectionDisplayConfigSchema = z.object({
  layout: CollectionDisplayLayoutSchema.default('grid'),
  columns: z.number().int().min(1).max(6).optional(),
  items_per_page: z.number().int().min(1).max(100).optional(),
  show_pagination: z.boolean().optional(),
  show_search: z.boolean().optional(),
  show_filters: z.boolean().optional(),
})
export type CollectionDisplayConfig = z.infer<typeof CollectionDisplayConfigSchema>

/**
 * Filter operator types
 */
export const FilterOperatorSchema = z.enum([
  'eq',       // equals
  'neq',      // not equals
  'in',       // in array
  'contains', // string contains
  'gt',       // greater than
  'gte',      // greater than or equal
  'lt',       // less than
  'lte',      // less than or equal
])
export type FilterOperator = z.infer<typeof FilterOperatorSchema>

/**
 * Filter configuration for collection items
 */
export const CollectionFilterSchema = z.object({
  field: z.string(),
  operator: FilterOperatorSchema,
  value: z.unknown(),
})
export type CollectionFilter = z.infer<typeof CollectionFilterSchema>

/**
 * Sort configuration
 */
export const CollectionSortSchema = z.object({
  field: z.string(),
  direction: z.enum(['asc', 'desc']).default('asc'),
})
export type CollectionSort = z.infer<typeof CollectionSortSchema>

/**
 * Item template configuration - how each item is displayed
 */
export const CollectionItemTemplateSchema = z.object({
  show_image: z.boolean().optional(),
  show_title: z.boolean().default(true),
  show_summary: z.boolean().optional(),
  show_date: z.boolean().optional(),
  link_to_detail: z.boolean().optional(),
  detail_page_pattern: z.string().optional(), // e.g., "/pois/{{slug}}"
  custom_fields: z.array(z.string()).optional(), // Additional fields to show
})
export type CollectionItemTemplate = z.infer<typeof CollectionItemTemplateSchema>

/**
 * Full collection embed configuration
 */
export const CollectionEmbedConfigSchema = z.object({
  // Collection Reference
  collection_type: z.string().optional(),           // Static: "pois", "events"
  collection_type_field: z.string().optional(),     // Dynamic: "{{page.poi_type}}"

  // Display
  display: CollectionDisplayConfigSchema,

  // Filtering
  filters: z.array(CollectionFilterSchema).optional(),
  default_sort: CollectionSortSchema.optional(),

  // Item Display
  item_template: CollectionItemTemplateSchema.optional(),

  // Limits
  max_items: z.number().int().min(1).optional(),
  published_only: z.boolean().default(true),
  featured_only: z.boolean().optional(),
})
export type CollectionEmbedConfig = z.infer<typeof CollectionEmbedConfigSchema>

// =============================================================================
// RESOLVED COLLECTION DATA (for rendering)
// =============================================================================

/**
 * Resolved collection item for rendering
 */
export interface ResolvedCollectionItem {
  id: string
  slug: string
  title: string        // from title_field
  summary?: string     // from summary_field
  image?: string       // from image_field
  date?: string        // from date_field
  data: Record<string, unknown>
  url?: string
  published: boolean
  featured: boolean
}

/**
 * Resolved collection metadata for rendering
 */
export interface ResolvedCollection {
  type: string
  displayName: string
  singularName?: string
  description?: string
  icon?: string
  color?: string
  titleField: string
  summaryField?: string
  imageField?: string
  dateField?: string
}

/**
 * Props passed to collection embed components
 */
export interface CollectionEmbedProps {
  config: CollectionEmbedConfig
  collection: ResolvedCollection
  items: ResolvedCollectionItem[]
  pagination?: {
    currentPage: number
    totalPages: number
    totalItems: number
    itemsPerPage: number
  }
}

// =============================================================================
// COLLECTION LISTING PAGE PROPS
// =============================================================================

/**
 * Props for collection listing pages (generated by site-builder)
 */
export interface CollectionListingProps {
  collection: ResolvedCollection
  items: ResolvedCollectionItem[]
  pagination: {
    currentPage: number
    totalPages: number
    totalItems: number
    itemsPerPage: number
    hasNextPage: boolean
    hasPrevPage: boolean
  }
  baseUrl: string // e.g., "/pois"
}

/**
 * Props for collection detail pages (generated by site-builder)
 */
export interface CollectionDetailProps {
  collection: ResolvedCollection
  item: ResolvedCollectionItem
  relatedItems?: ResolvedCollectionItem[]
  prevItem?: Pick<ResolvedCollectionItem, 'slug' | 'title' | 'url'>
  nextItem?: Pick<ResolvedCollectionItem, 'slug' | 'title' | 'url'>
}

// =============================================================================
// BLUEPRINT COMPONENT TYPE
// =============================================================================

/**
 * Collection embed as a blueprint component
 */
export const CollectionEmbedComponentSchema = z.object({
  type: z.literal('collection-embed'),
  order: z.number().int().min(0),
  config: CollectionEmbedConfigSchema,
  // Standard blueprint component fields
  id: z.string().uuid().optional(),
  visible: z.boolean().default(true),
  className: z.string().optional(),
  containerClassName: z.string().optional(),
})
export type CollectionEmbedComponent = z.infer<typeof CollectionEmbedComponentSchema>

// =============================================================================
// VALIDATION HELPERS
// =============================================================================

/**
 * Validate collection embed configuration
 */
export function validateCollectionEmbedConfig(config: unknown): {
  success: boolean
  data?: CollectionEmbedConfig
  error?: z.ZodError
} {
  const result = CollectionEmbedConfigSchema.safeParse(config)
  if (result.success) {
    return { success: true, data: result.data }
  }
  return { success: false, error: result.error }
}

/**
 * Get default collection embed config
 */
export function getDefaultCollectionEmbedConfig(): CollectionEmbedConfig {
  return {
    display: {
      layout: 'grid',
      columns: 3,
      items_per_page: 12,
      show_pagination: true,
      show_search: false,
      show_filters: false,
    },
    published_only: true,
  }
}
