/**
 * A tool graph's bundle entry (design §7.1). The manifest comes from Rust
 * (`blueprint::tools::manifest`, `entry.bundle: "tool.js"`); this writes the
 * entry source `swarmpress build` bundles: the graph and its types embedded
 * as JSON, and the shared interpreter as the skill.
 */
import { canonicalJson } from "@swarm-press/sdk/runtime";
import type { ToolGraph } from "./graph.ts";

export interface EntryOptions {
  /** Where the entry imports `toolSkill` from. Default `@swarm-press/toolgraph/skill`. */
  importFrom?: string;
}

/** The JS entry source of a tool's skill bundle (`export default toolSkill(graph, types)`). */
export function toolEntrySource(graph: ToolGraph, types: Record<string, unknown>, opts: EntryOptions = {}): string {
  const from = opts.importFrom ?? "@swarm-press/toolgraph/skill";
  return [
    `// The skill of tool ${JSON.stringify(graph.id)} (swarmpress.tool.v1), generated by @swarm-press/toolgraph.`,
    "// The graph is data; the interpreter is the shared, reviewed code. Do not edit: regenerate.",
    `import { toolSkill } from ${JSON.stringify(from)};`,
    "",
    `const graph = ${canonicalJson(graph)};`,
    `const types = ${canonicalJson(types)};`,
    "",
    "export default toolSkill(graph, types);",
    "",
  ].join("\n");
}
