#!/usr/bin/env tsx
/**
 * End-to-End Integration Test
 *
 * Drives a real run of contentProductionWorkflow against live infrastructure
 * (PostgreSQL, NATS, Temporal). Use this to verify the system works after
 * docker-compose / migrations / worker changes.
 *
 *   docker compose up -d
 *   pnpm --filter @swarm-press/workflows dev   # in another terminal
 *   tsx scripts/test-e2e.ts
 *
 * For the lightweight, mocked unit-style version that does not need
 * docker, see scripts/test-workflow-mock.ts.
 *
 * Exit codes:
 *   0 - all assertions passed
 *   1 - any assertion failed (infra missing, workflow stuck, etc.)
 */

import { v4 as uuidv4 } from 'uuid'
import pg from 'pg'
import { Client as TemporalClient, Connection as TemporalConnection } from '@temporalio/client'
import { connect as natsConnect, type NatsConnection } from 'nats'

const DATABASE_URL =
  process.env.DATABASE_URL || 'postgresql://swarmpress:swarmpress@localhost:5432/swarmpress'
const TEMPORAL_URL = process.env.TEMPORAL_URL || 'localhost:7233'
const NATS_URL = process.env.NATS_URL || 'nats://localhost:4222'
const TASK_QUEUE = process.env.TASK_QUEUE || 'swarmpress-content-production'
const TIMEOUT_MS = Number(process.env.E2E_TIMEOUT_MS || 60_000)

const REQUIRED_TABLES = [
  'companies',
  'departments',
  'roles',
  'agents',
  'websites',
  'content_items',
  'tasks',
  'state_audit_log',
]

function log(msg: string): void {
  console.log(`[e2e] ${msg}`)
}

function fail(msg: string): never {
  console.error(`[e2e] FAIL: ${msg}`)
  process.exit(1)
}

async function ensurePostgres(): Promise<pg.Client> {
  const client = new pg.Client({ connectionString: DATABASE_URL, connectionTimeoutMillis: 3000 })
  try {
    await client.connect()
  } catch (err) {
    fail(
      `cannot connect to PostgreSQL at ${DATABASE_URL}. ` +
        `Is docker compose up? (${(err as Error).message})`
    )
  }

  for (const table of REQUIRED_TABLES) {
    const r = await client.query(
      `SELECT to_regclass($1) IS NOT NULL AS exists`,
      [`public.${table}`]
    )
    if (!r.rows[0]?.exists) {
      await client.end().catch(() => undefined)
      fail(`missing table "${table}". Did migrations run? (000_schema.sql)`)
    }
  }
  log(`postgres ok (${REQUIRED_TABLES.length} core tables present)`)
  return client
}

async function ensureNats(): Promise<NatsConnection> {
  let nc: NatsConnection
  try {
    nc = await natsConnect({ servers: NATS_URL, timeout: 3000, name: 'swarmpress-e2e' })
  } catch (err) {
    fail(`cannot connect to NATS at ${NATS_URL} (${(err as Error).message})`)
  }
  log(`nats ok (${NATS_URL})`)
  return nc!
}

async function ensureTemporal(): Promise<TemporalClient> {
  let connection: TemporalConnection
  try {
    connection = await TemporalConnection.connect({ address: TEMPORAL_URL })
  } catch (err) {
    fail(`cannot connect to Temporal at ${TEMPORAL_URL} (${(err as Error).message})`)
  }
  // We can't trivially probe whether a worker is polling without starting a
  // workflow, but we can list task queues' reachability via describe.
  const client = new TemporalClient({ connection })
  log(`temporal ok (${TEMPORAL_URL})`)
  return client
}

async function findSeed(pgClient: pg.Client): Promise<{ websiteId: string; writerAgentId: string }> {
  const websiteRes = await pgClient.query(
    `SELECT id FROM websites ORDER BY created_at ASC NULLS LAST LIMIT 1`
  )
  if (!websiteRes.rows[0]) {
    fail('no website rows found. Run `tsx scripts/seed.ts` first.')
  }
  const agentRes = await pgClient.query(
    `SELECT a.id FROM agents a
     JOIN roles r ON a.role_id = r.id
     WHERE r.name ILIKE '%writer%'
     LIMIT 1`
  )
  if (!agentRes.rows[0]) {
    fail('no writer agent found. Run `tsx scripts/seed.ts` first.')
  }
  return { websiteId: websiteRes.rows[0].id, writerAgentId: agentRes.rows[0].id }
}

async function insertBrief(
  pgClient: pg.Client,
  websiteId: string,
  writerAgentId: string
): Promise<string> {
  const contentId = uuidv4()
  await pgClient.query(
    `INSERT INTO content_items
       (id, title, slug, brief, body, status, website_id, author_agent_id, metadata)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
    [
      contentId,
      'E2E test article',
      `e2e-test-${contentId.slice(0, 8)}`,
      'End-to-end test brief generated by scripts/test-e2e.ts',
      JSON.stringify([]),
      'brief_created',
      websiteId,
      writerAgentId,
      JSON.stringify({ e2e: true }),
    ]
  )
  log(`inserted brief content_items.id=${contentId}`)
  return contentId
}

async function pollTerminalState(
  pgClient: pg.Client,
  contentId: string
): Promise<string> {
  const TERMINAL = new Set(['published', 'rejected', 'archived', 'failed'])
  const deadline = Date.now() + TIMEOUT_MS
  let lastStatus = ''
  while (Date.now() < deadline) {
    const r = await pgClient.query(`SELECT status FROM content_items WHERE id = $1`, [contentId])
    const status: string = r.rows[0]?.status ?? 'missing'
    if (status !== lastStatus) {
      log(`status -> ${status}`)
      lastStatus = status
    }
    if (TERMINAL.has(status)) return status
    await new Promise((res) => setTimeout(res, 1000))
  }
  fail(`workflow did not reach a terminal state in ${TIMEOUT_MS}ms (last: ${lastStatus})`)
}

async function main(): Promise<void> {
  console.log('=== swarm.press end-to-end integration test ===')

  const pgClient = await ensurePostgres()
  const nats = await ensureNats()
  const temporal = await ensureTemporal()

  // Subscribe to all CloudEvents on the swarmpress.> wildcard
  let eventCount = 0
  const sub = nats.subscribe('swarmpress.>')
  ;(async () => {
    for await (const _msg of sub) eventCount++
  })().catch(() => undefined)

  const { websiteId, writerAgentId } = await findSeed(pgClient)
  const contentId = await insertBrief(pgClient, websiteId, writerAgentId)

  let terminalStatus = ''
  try {
    const workflowId = `e2e-content-production-${contentId}`
    log(`starting workflow ${workflowId} on queue ${TASK_QUEUE}`)
    const handle = await temporal.workflow.start('contentProductionWorkflow', {
      args: [{ contentId, writerAgentId, brief: 'E2E test brief', maxRevisions: 1 }],
      taskQueue: TASK_QUEUE,
      workflowId,
    })
    log(`workflow run id ${handle.firstExecutionRunId}`)

    terminalStatus = await pollTerminalState(pgClient, contentId)

    // Audit-log assertion: the state machine should have written transitions.
    const auditRes = await pgClient.query(
      `SELECT count(*)::int AS n FROM state_audit_log WHERE entity_id = $1`,
      [contentId]
    )
    const auditCount: number = auditRes.rows[0]?.n ?? 0
    if (auditCount === 0) {
      fail(`no state_audit_log rows for content ${contentId} (expected at least one)`)
    }
    log(`state_audit_log rows: ${auditCount}`)

    // Allow events one final tick to flush before we assert.
    await new Promise((res) => setTimeout(res, 500))
    if (eventCount === 0) {
      fail('expected at least one CloudEvent on swarmpress.> during the run')
    }
    log(`captured ${eventCount} cloudevents on swarmpress.>`)
  } finally {
    sub.unsubscribe()
    await pgClient.query(`DELETE FROM content_items WHERE id = $1`, [contentId]).catch(() => undefined)
    await pgClient.end().catch(() => undefined)
    await nats.drain().catch(() => undefined)
  }

  if (terminalStatus !== 'published') {
    fail(`workflow ended in non-success terminal state: ${terminalStatus}`)
  }
  log('all assertions passed')
}

main().catch((err) => {
  console.error('[e2e] uncaught error:', err)
  process.exit(1)
})
