/**
 * `kit blocks-doc` — writer-facing Markdown generated from the block schemas
 * (core + the site's custom `x:` blocks), never hand-written (ADR-0014).
 */
import { LINK_KEYS, MEDIA_KEYS, STRUCTURAL_KEYS, coreBlockSchemasV1, type JsonSchema } from '@swarm-press/content-schema'
import type { CustomBlockDef } from './content/load'

type S = Record<string, any>

function typeOf(s: S | undefined): string {
  if (!s) return 'any'
  if (s.const !== undefined) return `\`${JSON.stringify(s.const)}\``
  if (Array.isArray(s.enum)) return s.enum.map((v: unknown) => `\`${String(v)}\``).join(' \\| ')
  if (Array.isArray(s.anyOf)) return s.anyOf.map((x: S) => typeOf(x)).join(' \\| ')
  if (s.type === 'array') return `${typeOf(s.items)}[]`
  if (s.type === 'object') {
    if (s.properties) return `{ ${Object.keys(s.properties).join(', ')} }`
    return 'object'
  }
  return String(s.type ?? 'any')
}

function kindNote(key: string, s: S | undefined): string {
  if (MEDIA_KEYS.includes(key)) return 'media: `media:<id>` (preferred) or URL'
  if (LINK_KEYS.includes(key)) return 'link (per-language allowed)'
  const isText = (x: S | undefined) => x?.type === 'string' && x.const === undefined && !x.enum && !x.format && !x.pattern
  if (STRUCTURAL_KEYS.includes(key)) return ''
  if (isText(s) || (s?.type === 'array' && isText(s.items))) return 'localizable text'
  return ''
}

function fieldsTable(schema: S): string[] {
  const props: Record<string, S> = schema.properties ?? {}
  const required = new Set<string>(schema.required ?? [])
  const rows = Object.entries(props)
    .filter(([k]) => k !== 'type')
    .map(([k, s]) => {
      const notes = [kindNote(k, s), s.default !== undefined ? `default ${JSON.stringify(s.default)}` : '', s.description ?? ''].filter(Boolean).join('; ')
      return `| \`${k}\` | ${typeOf(s)} | ${required.has(k) ? 'yes' : ''} | ${notes} |`
    })
  if (!rows.length) return ['_No fields._']
  return ['| Field | Type | Required | Notes |', '|---|---|---|---|', ...rows]
}

export function blocksDoc(custom: CustomBlockDef[] = [], opts: { title?: string } = {}): string {
  const out: string[] = [
    `# ${opts.title ?? 'Content blocks'}`,
    '',
    '_Generated by `kit blocks-doc` from the block schemas. Do not edit by hand._',
    '',
    'Every page body is a list of blocks discriminated by `type`. Text fields accept a plain string or a',
    'localized object `{ "en": "…", "de": "…" }` (`en` required). Media fields take `media:<id>` from',
    '`content/config/media-index.json`. Internal links must point at existing pages.',
    '',
  ]
  out.push('## Core blocks', '')
  for (const [type, schema] of coreBlockSchemasV1()) {
    out.push(`### \`${type}\``, '', ...fieldsTable(schema as S), '')
  }
  if (custom.length) {
    out.push('## Site custom blocks', '')
    for (const c of custom) {
      const s = c.schema as S
      out.push(`### \`${c.type}\``, '')
      if (s?.description) out.push(String(s.description), '')
      out.push(...fieldsTable(s ?? {}), '')
      if (c.example !== undefined) out.push('Example:', '', '```json', JSON.stringify(c.example, null, 2), '```', '')
    }
  }
  return out.join('\n')
}

export type { JsonSchema }
