/**
 * `siteKit()` — the Astro 5 integration. It owns everything but presentation:
 * injected routes, content loading + validation (build fails on new errors),
 * SEO head, sitemap/robots, the tracker tag, link/media resolution and the
 * theme wiring. Themes are discovered from the theme dir (see `theme.ts`).
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, isAbsolute, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import tailwindcss from '@tailwindcss/vite'
import type { AstroIntegration } from 'astro'
import { CORE_BLOCK_TYPES } from '@swarm-press/content-schema'
import { loadSite } from './content/load'
import { applyBaseline, formatFinding, readBaseline, type Finding } from './findings'
import { loadManifest } from './manifest/load'
import type { SiteManifestInput } from './manifest/schema'
import { brokenLinkFindings, checkLinksIn, checkMediaIn, type BrokenLink } from './resolve'
import { planRoutes } from './routes/plan'
import { CHROME_NAMES, LAYOUT_NAMES } from './theme'
import { DEFAULT_TOKENS, mergeTokens, tokensToCss, type DesignTokens } from './tokens'

export interface SiteKitOptions {
  /** Content dir, relative to the project root. Default `content`. */
  contentDir?: string
  /** Manifest file (relative to root) or inline object. Default `site.manifest.json`. */
  manifest?: string | SiteManifestInput
  /** Theme dir (relative to root). Default: the manifest's `themeDir` (`theme`). */
  theme?: string
  /** Ratchet baseline file (relative to root). Default `kit-baseline.json` when it exists. */
  baseline?: string
  /** Infer a manifest from legacy config when no manifest file exists. Default false. */
  inferManifest?: boolean
  /** Compile Tailwind 4 (tokens become `@theme`). Default true. */
  tailwind?: boolean
  /** Fail the build on content errors not covered by the baseline. Default true. */
  failOnInvalid?: boolean
  /** Add the dev-only block gallery at `/_kit/blocks`. Default true. */
  gallery?: boolean
  /** Override the manifest's `base` (preview deploys under `/<company>/<pr>/`). */
  base?: string
}

const here = dirname(fileURLToPath(import.meta.url))
const KIT_ROOT = resolve(here, '..')
const ROUTES = join(KIT_ROOT, 'routes')
const posix = (p: string) => p.split('\\').join('/')

function discoverTheme(themeAbs: string, customTypes: Set<string>) {
  const imports: string[] = []
  const entries = { layouts: [] as string[], chrome: [] as string[], blocks: [] as string[], custom: [] as string[], strings: [] as string[] }
  let i = 0
  const add = (bucket: keyof typeof entries, key: string, file: string) => {
    const id = `_${bucket}${i++}`
    imports.push(`import ${id} from ${JSON.stringify(posix(file))};`)
    entries[bucket].push(`${JSON.stringify(key)}: ${id}`)
  }
  for (const n of LAYOUT_NAMES) {
    const f = join(themeAbs, 'layouts', `${n}.astro`)
    if (existsSync(f)) add('layouts', n, f)
  }
  for (const n of CHROME_NAMES) {
    const f = join(themeAbs, 'chrome', `${n}.astro`)
    if (existsSync(f)) add('chrome', n, f)
  }
  const blocksDir = join(themeAbs, 'blocks')
  if (existsSync(blocksDir)) {
    for (const n of readdirSync(blocksDir).sort()) {
      const full = join(blocksDir, n)
      if (n.endsWith('.astro') && CORE_BLOCK_TYPES.includes(n.slice(0, -6))) add('blocks', n.slice(0, -6), full)
      else if (statSync(full).isDirectory() && customTypes.has(`x:${n}`) && existsSync(join(full, 'Component.astro'))) {
        add('custom', `x:${n}`, join(full, 'Component.astro'))
      }
    }
  }
  const i18nDir = join(themeAbs, 'i18n')
  if (existsSync(i18nDir)) {
    for (const n of readdirSync(i18nDir).sort()) if (n.endsWith('.json')) add('strings', n.slice(0, -5), join(i18nDir, n))
  }
  const cfg = ['theme.config.ts', 'theme.config.mjs', 'theme.config.js'].map((f) => join(themeAbs, f)).find(existsSync)
  return [
    ...imports,
    cfg ? `import userTheme from ${JSON.stringify(posix(cfg))};` : 'const userTheme = undefined;',
    `export const discovered = {`,
    ...(['layouts', 'chrome', 'blocks', 'custom', 'strings'] as const).map((b) => `  ${b}: { ${entries[b].join(', ')} },`),
    `};`,
    `export default userTheme;`,
  ].join('\n')
}

function siteCss(themeAbs: string, tailwind: boolean): string {
  let tokens: DesignTokens = DEFAULT_TOKENS
  const tokenFile = join(themeAbs, 'tokens.json')
  if (existsSync(tokenFile)) tokens = mergeTokens(DEFAULT_TOKENS, JSON.parse(readFileSync(tokenFile, 'utf8')) as DesignTokens)
  const css = tokensToCss(tokens)
  const lines = ['/* Generated by @swarm-press/site-kit — do not edit. Source: theme/tokens.json */']
  if (tailwind) {
    const req = createRequire(join(KIT_ROOT, 'package.json'))
    const tw = dirname(req.resolve('tailwindcss/package.json'))
    lines.push(
      '@layer theme, base, components, utilities;',
      `@import ${JSON.stringify(posix(join(tw, 'theme.css')))} layer(theme);`,
      `@import ${JSON.stringify(posix(join(tw, 'preflight.css')))} layer(base);`,
      `@import ${JSON.stringify(posix(join(tw, 'utilities.css')))} layer(utilities);`,
      `@source ${JSON.stringify(posix(themeAbs))};`,
      `@source ${JSON.stringify(posix(join(KIT_ROOT, 'components')))};`,
      css.theme,
    )
  }
  lines.push(css.root)
  lines.push(`@import ${JSON.stringify(posix(join(KIT_ROOT, 'styles', 'kit.css')))};`)
  const themeCss = join(themeAbs, 'styles.css')
  if (existsSync(themeCss)) lines.push(`@import ${JSON.stringify(posix(themeCss))};`)
  return lines.join('\n') + '\n'
}

export default function siteKit(options: SiteKitOptions = {}): AstroIntegration {
  return {
    name: '@swarm-press/site-kit',
    hooks: {
      'astro:config:setup': async ({ config, updateConfig, injectRoute, logger, command }) => {
        const root = fileURLToPath(config.root)
        const contentDir = options.contentDir ?? 'content'
        const resolved = loadManifest(root, { manifest: options.manifest, contentDir, infer: options.inferManifest })
        const manifest = options.base ? { ...resolved.manifest, base: `/${options.base.replace(/^\/+|\/+$/g, '')}/`.replace(/^\/\/$/, '/') } : resolved.manifest
        if (resolved.source === 'inferred') logger.warn(`no site.manifest.json; inferred one (${resolved.notes.join('; ')})`)
        const themeDir = options.theme ?? manifest.themeDir
        const themeAbs = isAbsolute(themeDir) ? themeDir : resolve(root, themeDir)
        const themeRel = posix(relative(root, themeAbs)) || '.'
        const kitDir = join(root, '.kit')
        mkdirSync(kitDir, { recursive: true })

        // Content validation (fails the build on new errors).
        const site = loadSite({ root, manifest, contentDir, themeDir: themeRel })
        const plan = planRoutes(site)
        const findings: Finding[] = [...site.findings, ...plan.findings]
        const known = new Set(plan.byPath.keys())
        const broken: BrokenLink[] = []
        let checked = 0
        for (const page of site.pages) {
          for (const lang of Object.keys(page.routes)) {
            const r = checkLinksIn(page.data.body, page.file, lang, { base: manifest.base, languages: manifest.languages, known }, [manifest.defaultLanguage, 'en'])
            checked += r.checked
            broken.push(...r.broken.map((b) => ({ ...b, path: `/body${b.path}` })))
          }
          findings.push(...checkMediaIn(page.data, page.file, site.media))
        }
        findings.push(...brokenLinkFindings(broken, 'warning'))
        writeFileSync(join(kitDir, 'link-report.json'), JSON.stringify({ generatedAt: new Date().toISOString(), checked, broken }, null, 2) + '\n')
        const baselinePath = options.baseline ?? 'kit-baseline.json'
        const baseline = applyBaseline(findings, readBaseline(join(root, baselinePath)))
        writeFileSync(
          join(kitDir, 'content-report.json'),
          JSON.stringify({ generatedAt: new Date().toISOString(), routes: plan.entries.length, findings, newErrors: baseline.newErrors.length, baselined: baseline.baselined.length, fixed: baseline.fixed }, null, 2) + '\n',
        )
        const warnings = findings.filter((f) => f.severity === 'warning')
        if (broken.length) logger.warn(`${broken.length} broken internal link(s) (closed world) — see .kit/link-report.json`)
        if (warnings.length) logger.info(`${warnings.length} content warning(s) — see .kit/content-report.json`)
        if (baseline.baselined.length) logger.info(`${baseline.baselined.length} baselined content error(s) tolerated (${baselinePath})`)
        if (baseline.newErrors.length) {
          const shown = baseline.newErrors.slice(0, 40).map((f) => '  ' + formatFinding(f))
          const msg = `content validation failed: ${baseline.newErrors.length} error(s) not in ${baselinePath}\n${shown.join('\n')}${baseline.newErrors.length > 40 ? `\n  … ${baseline.newErrors.length - 40} more in .kit/content-report.json` : ''}`
          if (options.failOnInvalid !== false) throw new Error(msg)
          logger.error(msg)
        }
        logger.info(`${plan.entries.length} routes in ${manifest.languages.length} language(s); theme ${themeRel}`)

        // Styles and theme wiring.
        const cssFile = join(kitDir, 'site.css')
        writeFileSync(cssFile, siteCss(themeAbs, options.tailwind !== false))
        const themeModule = discoverTheme(themeAbs, new Set(site.customBlocks.filter((c) => c.hasComponent).map((c) => c.type)))
        const runtimeConfig = {
          root,
          contentDir,
          themeDir: themeRel,
          manifest,
          dev: command === 'dev',
          buildYear: new Date().getFullYear(),
        }
        const VIRTUAL: Record<string, string> = {
          'virtual:site-kit/config': `export default ${JSON.stringify(runtimeConfig)};`,
          'virtual:site-kit/theme': themeModule,
          'virtual:site-kit/styles': `import ${JSON.stringify(posix(cssFile))};`,
        }
        const plugins: unknown[] = [
          {
            name: 'site-kit:virtual',
            resolveId(id: string) {
              return id in VIRTUAL ? '\0' + id : undefined
            },
            load(id: string) {
              return id.startsWith('\0virtual:site-kit/') ? VIRTUAL[id.slice(1)] : undefined
            },
          },
        ]
        if (options.tailwind !== false) {
          plugins.push(tailwindcss())
        }
        updateConfig({
          site: manifest.baseUrl,
          base: manifest.base,
          trailingSlash: 'ignore',
          build: { format: 'directory' },
          vite: {
            plugins: plugins as never,
            ssr: { noExternal: ['@swarm-press/site-kit'] },
            server: { fs: { allow: [root, KIT_ROOT, themeAbs] } },
          },
        })

        const route = (pattern: string, file: string) => injectRoute({ pattern, entrypoint: join(ROUTES, file), prerender: true })
        route('/', 'root.astro')
        route('/404', '404.astro')
        route('/sitemap.xml', 'sitemap.xml.ts')
        route('/robots.txt', 'robots.txt.ts')
        route('/[lang]', 'home.astro')
        route('/[lang]/[region]', 'region.astro')
        route('/[lang]/[section]', 'section.astro')
        route('/[lang]/[region]/[section]', 'region-section.astro')
        route('/[lang]/[collection]/[item]', 'collection-item.astro')
        route('/[lang]/blog/[slug]', 'blog-post.astro')
        route('/[lang]/[...slug]', 'page.astro')
        if (command === 'dev' && options.gallery !== false) route('/_kit/blocks', 'gallery.astro')
      },
    },
  }
}
